site_name: Simple Python Template
site_url: http://localhost
repo_url: https://github.com/jymchng/simple-python-template
repo_name: jymchng/simple-python-template

nav:
  - Home:
      - index.md
      - General Tools: general-tools.md
      - Python Tools: python-tools.md
      - Documentation: docs.md
  - How To Use:
      - Download and Installation of Tools: how-to-use/download.md
      - Definitions: how-to-use/definitions.md
      - Minimally Supported Python Version: how-to-use/MSPV.md
      - Using `init.sh`: how-to-use/running-init-dot-sh.md
  - API Reference:
      - Lib: reference/lib.md
      - _c_extension: reference/_c_extension.md
      - main: reference/main.md
      - custom: reference/custom.md

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - content.tabs.link
        - content.code.copy
        - content.action.edit
        - search.highlight
        - search.share
        - search.suggest
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - toc.follow

    icon:
        repo: fontawesome/brands/github

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/jymchng/simple-python-template
          name: simple-python-template repository
        - icon: material/heart
          link: https://github.com/sponsors/jymchng/
          name: support simple-python-template

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences
    - attr_list
    - md_in_html

plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: true
            find_stubs_package: true
            allow_inspection: false # to remove __file__ etc from c extension stubs
          source:
            - '**/*.pyi'
            - '!**/*.so'  # Exclude .so files
            - '!**/*.pyd'  # Exclude .so files
